language: node_js
node_js: '12'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services:
  - mongodb
script:
  - npm start &
  - npm test
  - cd client && npm install && npm run test
